#!/usr/bin/env bash

OS_TYPE="$(uname -s)"

if [[ "$OS_TYPE" = "Darwin" ]]; then
  ./script/macos/bundle "$@"
elif [[ "$OS_TYPE" = "Linux" ]]; then
  ./script/linux/bundle "$@"
else
  echo "No bundle script defined for the current platform ($OS_TYPE)!"
  exit 1
fi
