[package]
name = "warp_tui"
edition = "2024"
description = "Term4u headless terminal interface"
authors.workspace = true
publish.workspace = true
license.workspace = true
autobins = false
default-run = "term4u-tui"

[[bin]]
name = "term4u-tui"
path = "src/bin/term4u.rs"

[dependencies]
anyhow.workspace = true
async-channel.workspace = true
clap.workspace = true
log.workspace = true
parking_lot.workspace = true
pathfinder_color.workspace = true
pathfinder_geometry.workspace = true
sum_tree.workspace = true
warp = { path = "../../app", default-features = false, features = ["local_only", "tui"] }
warp_core.workspace = true
warp_terminal.workspace = true
warpui.workspace = true
warpui_core = { workspace = true, features = ["tui"] }

[dev-dependencies]
command.workspace = true
warp = { path = "../../app", default-features = false, features = [
  "local_only",
  "test-util",
  "tui",
] }
warp_core = { workspace = true, features = ["test-util"] }

[features]
offline_hard = ["warp/offline_hard", "warp_core/offline_hard"]
test-util = ["warp/test-util", "warp_core/test-util"]
release_bundle = ["warp/release_bundle"]
standalone = ["warp/standalone"]
